---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400
  when: ansible_os_family == 'Debian'

- name: Install gcc and git
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - gcc
    - git

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- include: setup-Redhat.yml
  when: ansible_os_family == 'RedHat'

- name: Include java
  include_role:
    name: geerlingguy.java

- name: Create rally config folder
  file:
    path: /root/.rally
    state: directory
    mode: 0755

- name: Use correct config
  template:
    src: rally.ini.j2
    dest: /root/.rally/rally.ini
...
