---
- name: Install gcc and git
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - gcc
    - git
    - python3-pip

- name: Install esrally with pip
  pip:
    name: esrally
    executable: pip3

- name: Create rally config folder
  file:
    path: /root/.rally
    state: directory
    mode: 0755

- name: Use correct config
  template:
    src: rally.ini.j2
    dest: /root/.rally/rally.ini
...
