---
- name: Update apt cache.
  apt: update_cache=yes cache_valid_time=86400

- name: Install pip3 on Debian
  package:
    name: python3-pip
    state: latest

- name: Install esrally with pip on Debian
  pip:
    name: esrally
    executable: pip3
...
