---
- name: Install pip-3 on Redhat
  package:
    name: python34-devel
    state: latest
    enablerepo: epel
  when: ansible_pkg_mgr == 'yum'

- name: Install pip-3 on Redhat
  package:
    name: "{{ item }}"
    state: latest
    enablerepo: epel
  with_items:
    - redhat-rpm-config
    - python3-devel
  when: ansible_pkg_mgr == 'dnf'


- include: install-pip.yml
  when: ansible_os_family == 'RedHat'

- name: Install esrally with pip on Redhat
  pip:
    name: esrally
    executable: pip3
...
