---
- name: Install pip-3 on Redhat
  package:
    name: "{{ item }}"
    state: latest
    enablerepo: epel
  with_items:
    - python34-devel

- include: install-pip.yml
  when: ansible_os_family == 'RedHat'

- name: Install esrally with pip on Redhat
  pip:
    name: esrally
    executable: pip3
...
